Setup sticky session for Kerberos and NTML HTTP Authentication
cloudfoundry/gorouter pull request #392
Opened 2024-02-03 00:56 UTC by mariash

When server responds with `WWW-Authenticate: Negotiate`, save VCAP_ID cookie on response to client so that subsequent request with `Authorization: Negotiate ...` will be directed to the same application instance.

See [RFC-4559](https://www.ietf.org/rfc/rfc4559.txt)

* [X] I have viewed signed and have submitted the Contributor License Agreement

* [X] I have made this pull request to the `main` branch

* [X] I have [run all the unit tests](https://github.com/cloudfoundry/routing-release#running-unit-and-integration-tests).

* [ ] (Optional) I have run Routing Acceptance Tests and Routing Smoke Tests

* [ ] (Optional) I have run CF Acceptance Tests

2024-02-03 09:19 UTC, maxmoehl commented
Can you please explain why the same behaviour cannot be achieved by having the server set the configured sticky session cookie (e.g. `JSESSIONID`) and using the already existing functionality?

2024-02-05 14:46 UTC, geofffranks commented
> Can you please explain why the same behaviour cannot be achieved by having the server set the configured sticky session cookie (e.g. `JSESSIONID`) and using the already existing functionality?

With NTLM + Kerberos based Integraded Windows Authentication, the authentication logic happens at a core library level for .Net, rather than something the application can control. No cookies can be set until after the auth has been successful. Sticky session cookies work great after the fact, but unfortunately not for IWA.

2024-02-06 15:01 UTC, domdom82 requested changes

2024-02-06 19:34 UTC, mariash commented on proxy/round_tripper/proxy_round_tripper.go
> +	shouldSetVCAPID := (containsAuthNegotiateHeader || requestContainsStickySessionCookies) && requestNotSentToRequestedApp
Great find! Thank you!

2024-02-07 10:33 UTC, domdom82 approved these changes

2024-02-07 13:11 UTC, merged

2024-02-07 15:55 UTC, geofffranks commented
@domdom82 
FYI, we added a config flag for enabling/disabling this in https://github.com/cloudfoundry/gorouter/pull/393 and https://github.com/cloudfoundry/routing-release/pull/387.