feat: log local TCP address
cloudfoundry/gorouter pull request #454
Opened 2024-11-08 14:17 UTC by maxmoehl

Summary
---------------

When troubleshooting issues related to keepalive it is often useful to be able to correlate multiple requests made over the same connection. A first step was to introduce the information on whether the request was made on a re-used connection or not which was done with a7dbf849. This commit adds the local address of the TCP connection which adds the capability to distinguish between multiple, parallel keep-alive connections by looking at the client port of gorouter for the backend connection.

- [x] Read the [Contributing document](../blob/-/.github/CONTRIBUTING.md).

Backward Compatibility
---------------
Breaking Change? **Yes**

2024-11-08 15:25 UTC, maxmoehl commented
The big question is: how do we proceed with such log changes which could be considered breaking? I don't think it's a healthy practice to keep adding flags for each and every individual log field we add 🤔

2024-11-08 19:14 UTC, maxmoehl commented
> sadly this is a breaking change (whomp)

That's what I was expecting 😄 

> Develop a more advanced config property that allows users to "opt in" to certain fields by name 1 by 1. So that way we can add new fields, but they can always opt in / out of certain ones. - Fixes this problem for the future. But this is more work. And this is just a config property for everything! Will operators even opt in to any of them!?

That's probably what I will be going for in this PR to prevent accumulating further config flags. Just a flat list, and if anyone needs special properties they can be added and exposed via this mechanism without breaking anyone.

> add an additional access-log file that's json-based for people to migrate to, and we deprecate the old one eventually. When it is json based we can add new properties without it being a breaking change. - Personally I love this idea, but it is definitely more work.

This is my preferred long-term solution, but it will require quite some effort so it's not clear when we will be able to invest.

2024-12-09 20:58 UTC, ameowlia commented on accesslog/schema/access_log_record_test.go
> +		Context("when extra_fields is set to [local_address]", func() {
Can you add an test for...
* when extra_fields does not contain local_address, then the local address is not tested.
* when extra_fields contains "meow" it ... does not error? logs? idk does something reasonable?

2024-12-09 20:59 UTC, ameowlia requested changes
❓ Can you add a PR to routing-release so I can deploy and test everything at once?

2024-12-16 07:26 UTC, maxmoehl commented
I've opened cloudfoundry/routing-release#448 as a draft as I'm still adding tests.

2025-01-17 12:34 UTC, maxmoehl commented on accesslog/schema/access_log_record_test.go
> +		Context("when extra_fields is set to [local_address]", func() {
I've added two more test cases.

2025-01-17 13:30 UTC, maxmoehl commented
The past weeks have been a bit busy, I finally found the time to clean this up. The [rr PR](https://github.com/cloudfoundry/routing-release/pull/448) is also ready now. Unfortunately test execution on my end is still hindered by cloudfoundry/routing-release#450. I ran the package tests using `go test` and they seem fine but I can't run the whole shebang, could you please do that? Thank you!

I'm currently also deploying this to one of our environments.

2025-01-21 20:40 UTC, ameowlia commented on accesslog/schema/access_log_record.go
> +	for _, field := range r.ExtraFields {
If we iterate over the list this means the operator will get to determine the order of these, vs a standardized order. 

Does that matter?

2025-01-21 20:45 UTC, ameowlia commented on proxy/round_tripper/proxy_round_tripper.go
> +				slog.String("local-addr", trace.LocalAddr()),
❓ Why call it "local-addr" here, but "local_address" above? Why not "local-address" here?

2025-01-21 20:46 UTC, ameowlia commented on proxy/round_tripper/proxy_round_tripper.go
> +				slog.String("local-addr", trace.LocalAddr()),
From reading your spec description on the other PR, it is not clear if the "extra_headers" property is only for access logs or not. 

❓ Based on my reading of it, I would've thought it would affect these logs too? Thoughts?

2025-01-21 20:47 UTC, ameowlia commented
✅ tests pass

2025-01-22 07:05 UTC, maxmoehl commented on proxy/round_tripper/proxy_round_tripper.go
> +				slog.String("local-addr", trace.LocalAddr()),
Hm, in the past we didn't give much thought to the compatibility of non-access-logs, primarily because these are JSON and we expect people to parse it as such. Additional fields shouldn't cause any breakage in those cases. For example the timing info directly above this line is controlled by a feature flag in the access logs but unconditionally included in this log.

2025-01-22 07:09 UTC, maxmoehl commented on accesslog/schema/access_log_record.go
> +	for _, field := range r.ExtraFields {
It probably does matter. The other thought I had is that you can end up with multiple instances of the same field (maybe you use some complex templating for the manifest and accidentally add it twice that way). What about this: during the creation of the access logger we de-duplicate the list and order it alphabetically. That way we have a consistent ordering and prevent people from having duplicate fields.

The only concern would then be if someone intentionally wants to influence the order for whatever reason but we usually don't allow that anyway.

2025-01-22 12:07 UTC, maxmoehl commented on proxy/round_tripper/proxy_round_tripper.go
> +				slog.String("local-addr", trace.LocalAddr()),
Fixed it.

2025-01-27 21:45 UTC, ameowlia commented on accesslog/schema/access_log_record.go
> +	for _, field := range r.ExtraFields {
> What about this: during the creation of the access logger we de-duplicate the list and order it alphabetically. That way we have a consistent ordering and prevent people from having duplicate fields.

I like the idea of de-duplicating.

I theoretically like the idea of alphabetizing, but I don't like that I think it would cause breaking changes. I know we only have one "extra field" here right now. But I think eventually we want to put all (most??) access logger fields to be controlled by this property, correct? And if it alphabetizes it, then the order would change.

tl;dr:
✅ deduping
⛔ alphabetizing imo

2025-01-27 21:46 UTC, ameowlia commented on proxy/round_tripper/proxy_round_tripper.go
> +				slog.String("local-addr", trace.LocalAddr()),
> I could adjust the wording in the release spec to reflect that clearly.

Sounds good to me.

2025-01-29 13:09 UTC, maxmoehl commented on accesslog/schema/access_log_record.go
> +	for _, field := range r.ExtraFields {
Fields are now de-duplicated!

2025-01-31 22:06 UTC, ameowlia approved these changes

2025-01-31 22:07 UTC, merged